### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mutateSelectedText' of undefined

### ISSUE THREAD

**Issue by benrobson** [rosston/sublime-word-navigation-atom#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [sublime-word-navigation](https://github.com/rosston/sublime-word-navigation-atom) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'mutateSelectedText' of undefined

```
At C:\Users\Anastasia\.atom\packages\sublime-word-navigation\lib\sublime-word-navigation.coffee:70

TypeError: Cannot read property 'mutateSelectedText' of undefined
    at Object.deleteToBeginningOfWord (/packages/sublime-word-navigation/lib/sublime-word-navigation.coffee:70:17)
    at /packages/sublime-word-navigation/lib/sublime-word-navigation.coffee:16:66)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.22.1/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.22.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.22.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:40.2.0 editor:select-to-end-of-line (input.hidden-input)
     -0:39.7.0 core:copy (input.hidden-input)
     -0:38.6.0 core:move-down (input.hidden-input)
     -0:38.4.0 core:paste (input.hidden-input)
     -0:37.3.0 core:cut (input.hidden-input)
  2x -0:37.3.0 core:undo (input.hidden-input)
     -0:36 core:paste (input.hidden-input)
     -0:34.5.0 editor:select-to-first-character-of-line (input.hidden-input)
  3x -0:34.2.0 core:backspace (input.hidden-input)
  7x -0:32.8.0 core:select-left (input.hidden-input)
     -0:29.3.0 core:save (input.hidden-input)
     -0:22.3.0 core:confirm (div.github-StagingView.unstaged-changes-focused)
  4x -0:18.9.0 core:backspace (input.hidden-input)
     -0:17.9.0 core:select-all (input.hidden-input)
     -0:17.8.0 sublime-word-navigation:delete-to-beginning-of-word (input.hidden-input)
  4x -0:16.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-wrap-in-tag 0.6.0 
auto-update-plus 0.5.6 
browse 1.10.5 
build 0.69.0 
busy 0.7.0 
busy-signal 1.4.3 
ctrl-dir-scroll 0.2.5 
minimap 4.29.7 
multi-cursor 2.1.5 
satisfy-dependencies 0.4.2 
set-syntax 0.4.0 
sublime 0.5.0 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.4 
sublime-word-navigation 0.2.0 
sublimify 0.10.0 
tag 0.5.0 
text-manipulation 0.6.0 
```

**Comment by rosston** [comment]
@shadowolfyt Sorry, getting to this late. Just tried this on Atom 1.22.1 and can't reproduce it. From [the code](https://github.com/rosston/sublime-word-navigation-atom/blob/3ac1b9fba655494b9357ca372de7cbfbb057e6c2/lib/sublime-word-navigation.coffee#L70), it looks like this could only happen if you didn't have an editor active. Are you still running into this issue?

**Comment by benrobson** [comment]
No, I am not.
